### ISSUE TITLE
 the miner is mining arrr/btc instead of zcash

### ISSUE THREAD

**Issue by CanisLRufus** [vertiond/verthash-one-click-miner#101]
hello i came across an issue when it comes to mining zcash from the zpool.
when i was mining zcash i didint earn the coin but when i viewed the payout info it was actually mining ARRR instead of ZEC dispite that i have zcash selected in the payout option

**Comment by vertiond** [comment]
I was able to verify that the payout info was incorrectly displayed upon using a ZEC sapling address and ZEC legacy addresses failed to register with their website.  

What does work are transparent ZEC address with a prefix of `t`.

The OCM is using `c=ZEC,zap=VTC` so everything is working correctly on its end.  This issue is with zpool.  I can only recommend that you use a transparent ZEC address and ask for further support in their discord. https://discord.gg/n45n6Jj
