### ISSUE TITLE
gpu select

### ISSUE THREAD

**Issue by D3adwe** [vertiond/verthash-one-click-miner#63]
hi, i have 2 gpu, how can i choose which gpu to use?

**Comment by D3adwe** [comment]
Maybe i found a solution, close OCM then go to device manager and disable the gpu we don't want to use, start OCM keep 2 min and then re-enable the gpu. 
For now it works but if someone add the option to choose directly from OCM it would be better, and if someoane have other solution please tell me txs.

**Comment by vertiond** [comment]
You'll have to run [VerthashMiner](https://github.com/CryptoGraphics/VerthashMiner) directly in order to configure that. This is a good idea but this program largely derives its updates to the core software from [upstream](https://github.com/vertcoin-project/one-click-miner-vnext) and will wait for them to support this before merging downstream.
